//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Salary_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryTicketDetail
    {
        public string SalaryTicketID { get; set; }
        public string WorkingTimeID { get; set; }
        public string AllowanceID { get; set; }
        public string TaxID { get; set; }
        public int WageTier { get; set; }
        public double BasicSalary { get; set; }
        public Nullable<double> FinalSalary { get; set; }
    }
}
