//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Salary_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingTime
    {
        public string WorkingTimeID { get; set; }
        public string EmployeeID { get; set; }
        public string PeriodID { get; set; }
        public double WorkedTime { get; set; }
    }
}
